- name: Check Agent state
  local_action:
    module: ansible.builtin.uri
    url: "{{ tantor_agent_url }}/integration/agents/register/check"
    body_format: json
    body:
      host: "{{ tantor_agent_host_ip }}"
    return_content: true
    validate_certs: "{{ tantor_agent_validate_certs }}"
    method: "POST"
    headers:
      Authorization: "Bearer {{ tantor_agent_token }}"
    status_code: [422, 200]
  become: false
  register: response

- name: Deregister agent
  shell: pmaagent deregister -y
  register: deregister_result
  failed_when: deregister_result.stderr != ""
  when: response.json.code == 'WORKSPACE.AGENT.CHECK.EXISTS'

