---

- include_tasks: install_agent_repo.yml
  when: tantor_agent_install_mode == 'repo'

- include_tasks: install_agent_local.yml
  when: tantor_agent_install_mode == 'local'

- name: Check version of agent
  command: pmaagent version -r
  register: agent_version

- include_tasks: agent_deregister.yml
  when: tantor_agent_install_mode in ('purge', 'deregister')

- include_tasks: agent_registration.yml
  when: tantor_agent_install_mode not in ('purge', 'deregister')

- include_tasks: delete_agent.yml
  when: tantor_agent_install_mode == 'purge'

