- name: Download deb package
  ansible.builtin.get_url:
    url: "{{ platform_url }}:{{ platform_repo_port }}/packages/pmaagent.deb"
    dest: /tmp/pmaagent.deb
    mode: '0644'
    validate_certs: "{{ platform_validate_certs }}"
  changed_when: true
  notify: Cleanup files from filesystem
  when: ansible_os_family in ("Debian", "Astra Linux")

- name: Download rpm package
  ansible.builtin.get_url:
    url: "{{ platform_url }}:{{ platform_repo_port }}/packages/pmaagent.rpm"
    dest: /tmp/pmaagent.rpm
    mode: '0644'
    validate_certs: "{{ platform_validate_certs }}"
  changed_when: true
  notify: Cleanup files from filesystem
  when: ansible_os_family in ("RedHat")

- name: Install package pmaagent
  ansible.builtin.apt:
    deb: /tmp/pmaagent.deb
    state: present
  notify: Restart pmaagent
  when: ansible_os_family in ("Debian", "Astra Linux")

- name: Install package pmaagent
  ansible.builtin.yum:
    name: /tmp/pmaagent.rpm
    state: present
  notify: Restart pmaagent
  when: ansible_os_family in ("RedHat")
